#include "instructions.h"

const char *CMDS[] = {
    "adc",
    "add",
    "addps",
    "and",
    "andnps",
    "andps",
    "bsf",
    "bsr",
    "call",
    "cbw",
    "cdq",
    "cdqe",
    "clc",
    "cld",
    "cli",
    "cmc",
    "cmova",
    "cmovae",
    "cmovb",
    "cmovbe",
    "cmovc",
    "cmove",
    "cmovg",
    "cmovge",
    "cmovl",
    "cmovle",
    "cmovna",
    "cmovnae",
    "cmovnb",
    "cmovnbe",
    "cmovnc",
    "cmovne",
    "cmovng",
    "cmovnge",
    "cmovnl",
    "cmovnle",
    "cmovno",
    "cmovnp",
    "cmovns",
    "cmovnz",
    "cmovo",
    "cmovp",
    "cmovpe",
    "cmovpo",
    "cmovs",
    "cmovz",
    "cmp",
    "cpuid",
    "cqo",
    "cwd",
    "cwde",
    "dec",
    "div",
    "divps",
    "fwait",
    "hlt",
    "idiv",
    "imul",
    "inc",
    "iret",
    "iretq",
    "ja",
    "jae",
    "jb",
    "jbe",
    "jc",
    "je",
    "jg",
    "jge",
    "jl",
    "jle",
    "jmp",
    "jne",
    "jnz",
    "jz",
    "lahf",
    "lea",
    "mov",
    "movaps",
    "movdqa",
    "movdqu",
    "movq",
    "movsx",
    "movups",
    "movzx",
    "mul",
    "mulps",
    "neg",
    "nop",
    "not",
    "or",
    "orps",
    "packssdw",
    "packsswb",
    "packuswb",
    "paddb",
    "paddd",
    "paddw",
    "pand",
    "pandn",
    "pause",
    "pcmpeqb",
    "pcmpeqd",
    "pcmpeqw",
    "pcmpgtb",
    "pcmpgtd",
    "pcmpgtw",
    "pmaxsw",
    "pmaxub",
    "pminsw",
    "pminub",
    "pmovmskb",
    "pop",
    "popf",
    "popfq",
    "por",
    "pslld",
    "pslldq",
    "psllq",
    "psllw",
    "psrad",
    "psraw",
    "psrld",
    "psrldq",
    "psrlq",
    "psrlw",
    "psubb",
    "psubd",
    "psubw",
    "punpckhbw",
    "punpckhdq",
    "punpckhqdq",
    "punpckhwd",
    "punpcklbw",
    "punpckldq",
    "punpcklqdq",
    "punpcklwd",
    "push",
    "pushf",
    "pushfq",
    "pxor",
    "rcl",
    "rcr",
    "rdpru", // NASM 3.02 does not support!
    "ret",
    "rol",
    "ror",
    "sahf",
    "sal",
    "sar",
    "sbb",
    "seta",
    "setae",
    "setb",
    "setbe",
    "setc",
    "sete",
    "setg",
    "setge",
    "setl",
    "setle",
    "setna",
    "setnae",
    "setnb",
    "setnbe",
    "setnc",
    "setne",
    "setng",
    "setnge",
    "setnl",
    "setnle",
    "setno",
    "setnp",
    "setns",
    "setnz",
    "seto",
    "setp",
    "setpe",
    "setpo",
    "sets",
    "setz",
    "shl",
    "shr",
    "stc",
    "std",
    "sti",
    "sub",
    "subps",
    "syscall",
    "test",
    "ud2",
    "vaddpd",
    "vaddps",
    "vaddsd",
    "vaddss",
    "vandpd",
    "vandps",
    "vcvtdq2ps",
    "vcvtpd2ps",
    "vcvtps2dq",
    "vcvtps2pd",
    "vcvttps2dq",
    "vdivpd",
    "vdivps",
    "vmaxpd",
    "vmaxps",
    "vmaxsh",
    "vminpd",
    "vminps",
    "vminsh",
    "vmovapd",
    "vmovaps",
    "vmovdqa",
    "vmovdqu",
    "vmovupd",
    "vmovups",
    "vmulpd",
    "vmulps",
    "vmulsd",
    "vmulss",
    "vorpd",
    "vorps",
    "vpackssdw",
    "vpacksswb",
    "vpackuswb",
    "vpaddb",
    "vpaddd",
    "vpaddq",
    "vpaddw",
    "vpand",
    "vpandn",
    "vpcmpeqb",
    "vpcmpeqd",
    "vpcmpeqw",
    "vpcmpgtb",
    "vpcmpgtd",
    "vpcmpgtw",
    "vpmaxsw",
    "vpmaxub",
    "vpminsw",
    "vpminub",
    "vpor",
    "vpslld",
    "vpsllq",
    "vpsllw",
    "vpsrad",
    "vpsraw",
    "vpsrld",
    "vpsrlq",
    "vpsrlw",
    "vpsubb",
    "vpsubd",
    "vpsubw",
    "vpunpckhbw",
    "vpunpckhdq",
    "vpunpckhqdq",
    "vpunpckhwd",
    "vpunpcklbw",
    "vpunpckldq",
    "vpunpcklqdq",
    "vpunpcklwd",
    "vpxor",
    "vsqrtpd",
    "vsqrtps",
    "vsubpd",
    "vsubps",
    "vxorpd",
    "vxorps",
    "wait",
    "xchg",
    "xor",
    "xorps",
    NULL
};

const int CMDS_COUNT = sizeof(CMDS) / sizeof(CMDS[0]) - 1;


const char *JCC[] = {
    "ja", "jae", "jb", "jbe", "jc", "je", "jg", "jge", "jl", "jle",
    "jne", "jnz", "jz", NULL
};

const int JCC_COUNT = sizeof(JCC) / sizeof(JCC[0]) -1;

const char *HUMAN_AST[] = {
    "db", "dd", "dq", "dw", NULL
};
const int HUMAN_AST_COUNT = sizeof(HUMAN_AST) / sizeof(HUMAN_AST[0]) -1;
const char *HUMAN_AST2[] = {
    "byte", "dword", "qword", "word", NULL
};
const int HUMAN_AST_COUNT2 = sizeof(HUMAN_AST2) / sizeof(HUMAN_AST2[0]) -1;

const char *Sign_extensions[] = {
    "cbw", "cdq", "cdqe", "cqo", "cwd", "cwde", NULL
};
const int Sign_extensions_COUNT = sizeof(Sign_extensions) / sizeof(Sign_extensions[0]) -1 ;

// sign-extended immediate instructions
const char *short_imm_instructions[] = {
    "adc", "add", "and", "cmp", "or", "sbb", "sub", "test", "xor", NULL
};

const int short_imm_instructions_COUNT = sizeof(short_imm_instructions) / sizeof(short_imm_instructions[0]) -1;

const char *zero_operand_instructions[] = {
    "clc", "cld", "cli", "cmc", "cpuid", "fwait", "hlt", "iret", "iretq",
    "lahf", "nop", "pause", "popf", "popfq", "pushf", "rdpru", "ret", "sahf", "stc",
    "std", "sti", "syscall", "ud2", "wait", NULL
};

const int zero_operand_instructions_COUNT = sizeof(zero_operand_instructions) / sizeof(zero_operand_instructions[0]) -1;

const char *AVX512[] = {
    "vaddpd",
    "vaddps",
    "vaddsd",
    "vaddss",
    "vandpd",
    "vandps",
    "vcvtdq2ps",
    "vcvtpd2ps",
    "vcvtps2dq",
    "vcvtps2pd",
    "vcvttps2dq",
    "vdivpd",
    "vdivps",
    "vmaxpd",
    "vmaxps",
    "vmaxsh",
    "vminpd",
    "vminps",
    "vminsh",
    "vmovapd",
    "vmovaps",
    "vmovdqa",
    "vmovdqu",
    "vmovupd",
    "vmovups",
    "vmulpd",
    "vmulps",
    "vmulsd",
    "vmulss",
    "vpackssdw",
    "vpacksswb",
    "vpackuswb",
    "vpaddb",
    "vpaddd",
    "vpaddq",
    "vpaddw",
    "vpand",
    "vpandn",
    "vpcmpeqb",
    "vpcmpeqd",
    "vpcmpeqw",
    "vpcmpgtb",
    "vpcmpgtd",
    "vpcmpgtw",
    "vpmaxsw",
    "vpmaxub",
    "vpminsw",
    "vpminub",
    "vpor",
    "vpslld",
    "vpsllq",
    "vpsllw",
    "vpsrad",
    "vpsraw",
    "vpsrld",
    "vpsrlq",
    "vpsrlw",
    "vpsubb",
    "vpsubd",
    "vpsubw",
    "vpunpckhbw",
    "vpunpckhdq",
    "vpunpckhqdq",
    "vpunpckhwd",
    "vpunpcklbw",
    "vpunpckldq",
    "vpunpcklqdq",
    "vpunpcklwd",
    "vpxor",
    "vsqrtpd",
    "vsqrtps",
    "vsubpd",
    "vsubps",
    "vxorpd",
    "vxorps",

    NULL
};

const int AVX512_COUNT = sizeof(AVX512) / sizeof(AVX512[0]) -1;

const char* AVX512_that_not_suppots_broatcast[] = {"vmaxsh", "vminsh", NULL};
const int AVX512_that_not_suppots_broatcast_COUNT = sizeof(AVX512_that_not_suppots_broatcast) / sizeof(AVX512_that_not_suppots_broatcast[0]) -1;

